

target 'SLListSwiftComponent_Example' do
  pod 'SLListSwiftComponent', :path => '../'

  target 'SLListSwiftComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
